export const STORE_CONFIG = Object.freeze({
  version: 1,
  duplicateRule: "protected",
  dailyResetHour: 0,
  offerDurationMs: 24 * 60 * 60 * 1000
});

export const STORE_TABS = Object.freeze([
  Object.freeze({ id: "featured", label: "Featured", icon: "\u2605" }),
  Object.freeze({ id: "decks", label: "Decks", icon: "\u25a3" }),
  Object.freeze({ id: "coins", label: "Coins", icon: "\u25c9" })
]);

const PRODUCTS = [
  {
    id: "daily-free-pack",
    productType: "daily_free_pack",
    displayName: "Free Daily Pack",
    subtitle: "A gift for you every day!",
    description: "Awards 1 random cosmetic card with duplicate protection.",
    artwork: "mystery-pack-purple",
    backgroundTheme: "green",
    currencyType: "free",
    cardsAwarded: 1,
    unlockEntireCollection: false,
    dailyLimit: 1,
    contents: ["1 random cosmetic card", "No duplicate cards"],
    sortOrder: 10,
    tabs: ["featured"],
    enabled: true
  },
  {
    id: "mystery-card-pack",
    productType: "generic_card_pack",
    displayName: "Mystery Card Pack",
    subtitle: "One card from any featured collection",
    description: "Awards 1 random cosmetic card. Rainbow chance: 3%.",
    artwork: "mystery-pack-gold",
    backgroundTheme: "purple",
    currencyType: "coins",
    coinPrice: 125,
    cardsAwarded: 1,
    unlockEntireCollection: false,
    rarityTable: "global",
    quantityLimit: 208,
    badge: "LIMITED",
    sortOrder: 20,
    tabs: ["featured"],
    enabled: true
  },
  {
    id: "pink-arcade-full-deck",
    productType: "full_deck",
    displayName: "Pink Arcade Full Deck",
    subtitle: "Complete 52-card collection",
    description: "Unlock all 52 supplied pixel cards and the custom neon trail.",
    artwork: "pink-arcade-deck",
    backgroundTheme: "pink",
    currencyType: "real_money",
    platformProductId: "card_crunch_full_deck_pink_arcade",
    localizedRealMoneyPrice: "$2.99",
    collectionId: "pink_arcade",
    unlockEntireCollection: true,
    contents: ["All 52 cards", "Neon trail", "Exclusive card back"],
    badge: "EXCLUSIVE",
    sortOrder: 30,
    tabs: ["featured", "decks"],
    enabled: true
  },
  {
    id: "bank-shield",
    productType: "utility",
    displayName: "Bank Shield",
    subtitle: "Save 25% when a run busts",
    description: "Arms one Safe Bank Shield for your next Pot run.",
    artwork: "bank-shield",
    backgroundTheme: "blue",
    currencyType: "coins",
    coinPrice: 500,
    unlockEntireCollection: false,
    sortOrder: 40,
    tabs: ["featured"],
    enabled: true
  },
  {
    id: "coin-drop-ad",
    productType: "rewarded_ad",
    displayName: "Coin Drop",
    subtitle: "Watch Ad \u2022 +125 Coins",
    description: "Up to 3 rewarded Coin Drops each day.",
    artwork: "coin-drop",
    backgroundTheme: "teal",
    currencyType: "rewarded_ad",
    rewardAmount: 125,
    dailyLimit: 3,
    unlockEntireCollection: false,
    sortOrder: 50,
    tabs: ["featured"],
    enabled: true
  },
  {
    id: "coin-vault",
    productType: "coin_bundle",
    displayName: "Coin Vault",
    subtitle: "1,500 Coins",
    description: "A bright stack of coins for packs and cosmetics.",
    artwork: "coin-vault",
    backgroundTheme: "gold",
    currencyType: "real_money",
    platformProductId: "card_crunch_coin_pack_1500",
    localizedRealMoneyPrice: "$1.99",
    coinAmount: 1500,
    unlockEntireCollection: false,
    badge: "BEST VALUE",
    sortOrder: 60,
    tabs: ["featured", "coins"],
    enabled: true
  },

  {
    id: "night-ink-pack",
    productType: "themed_card_pack",
    displayName: "Night Ink Pack",
    subtitle: "Awards 1 random Night Ink card",
    description: "Build the dark-mode paper collection one exact card at a time.",
    artwork: "night-pack",
    backgroundTheme: "blue",
    currencyType: "coins",
    coinPrice: 500,
    collectionId: "dark",
    cardsAwarded: 1,
    unlockEntireCollection: false,
    rarityTable: "dark",
    sortOrder: 110,
    tabs: ["decks"],
    enabled: true
  },
  {
    id: "pink-pop-pack",
    productType: "themed_card_pack",
    displayName: "Pink Pop Pack",
    subtitle: "Awards 1 random Pink Pop card",
    description: "Collect berry-icing cards with duplicate protection.",
    artwork: "pink-pack",
    backgroundTheme: "pink",
    currencyType: "coins",
    coinPrice: 650,
    collectionId: "pink",
    cardsAwarded: 1,
    unlockEntireCollection: false,
    rarityTable: "pink",
    sortOrder: 120,
    tabs: ["decks"],
    enabled: true
  },
  {
    id: "glitch-gold-pack",
    productType: "themed_card_pack",
    displayName: "Glitch Gold Pack",
    subtitle: "Awards 1 random Glitch Gold card",
    description: "One gilded cosmetic card. This is not the full deck.",
    artwork: "gold-pack",
    backgroundTheme: "gold",
    currencyType: "coins",
    coinPrice: 900,
    collectionId: "gold",
    cardsAwarded: 1,
    unlockEntireCollection: false,
    rarityTable: "gold",
    sortOrder: 130,
    tabs: ["decks"],
    enabled: true
  },
  {
    id: "rainbow-rush-pack",
    productType: "themed_card_pack",
    displayName: "Rainbow Rush Pack",
    subtitle: "Awards 1 random Rainbow Rush card",
    description: "A rare animated cosmetic card with prismatic trail effects.",
    artwork: "rainbow-pack",
    backgroundTheme: "purple",
    currencyType: "coins",
    coinPrice: 1200,
    collectionId: "rainbow",
    cardsAwarded: 1,
    unlockEntireCollection: false,
    rarityTable: "rainbow",
    badge: "MYTHIC",
    sortOrder: 140,
    tabs: ["decks"],
    enabled: true
  },
  {
    id: "gold-royale-full-deck",
    productType: "full_deck",
    displayName: "Glitch Gold Full Deck",
    subtitle: "Unlock all 52 cards",
    description: "Complete collection with animated gold glitch effects.",
    artwork: "gold-deck",
    backgroundTheme: "gold",
    currencyType: "real_money",
    platformProductId: "card_crunch_full_deck_gold",
    localizedRealMoneyPrice: "$4.99",
    collectionId: "gold",
    unlockEntireCollection: true,
    contents: ["All 52 Glitch Gold cards", "Gold trail", "Exclusive card back"],
    badge: "FULL DECK",
    sortOrder: 210,
    tabs: ["decks"],
    enabled: true
  },
  {
    id: "royal-prism-full-deck",
    productType: "full_deck",
    displayName: "Royal Prism Full Deck",
    subtitle: "Complete animated 52-card collection",
    description: "Prismatic card faces, card back, smear trail, and effects.",
    artwork: "prism-deck",
    backgroundTheme: "premium",
    currencyType: "real_money",
    platformProductId: "card_crunch_full_deck_rainbow",
    localizedRealMoneyPrice: "$4.99",
    collectionId: "rainbow",
    unlockEntireCollection: true,
    contents: ["All 52 Royal Prism cards", "Prismatic card back", "Rainbow trail"],
    badge: "EXCLUSIVE",
    sortOrder: 220,
    tabs: ["decks", "coins"],
    enabled: true
  },
  {
    id: "pixel-flame-trail",
    productType: "trail",
    displayName: "Pixel Flame Trail",
    subtitle: "Leave a trail of fire",
    description: "A standalone card-flight cosmetic.",
    artwork: "flame-trail",
    backgroundTheme: "gold",
    currencyType: "coins",
    coinPrice: 300,
    cosmeticSlot: "trail",
    cosmeticId: "pixel_flame",
    unlockEntireCollection: false,
    sortOrder: 310,
    tabs: ["decks"],
    enabled: true
  },
  {
    id: "holo-card-back",
    productType: "card_back",
    displayName: "Holo Card Back",
    subtitle: "Shimmer with holographic style",
    description: "A standalone card-back cosmetic.",
    artwork: "holo-back",
    backgroundTheme: "blue",
    currencyType: "coins",
    coinPrice: 250,
    cosmeticSlot: "cardBack",
    cosmeticId: "holo",
    unlockEntireCollection: false,
    sortOrder: 320,
    tabs: ["decks"],
    enabled: true
  },

  {
    id: "daily-coin-bonus",
    productType: "daily_coin_bonus",
    displayName: "Free Daily Bonus",
    subtitle: "Claim 50 Coins",
    description: "A free coin pile every day.",
    artwork: "coin-pile",
    backgroundTheme: "green",
    currencyType: "free",
    coinAmount: 50,
    dailyLimit: 1,
    unlockEntireCollection: false,
    sortOrder: 410,
    tabs: ["coins"],
    enabled: true
  },
  {
    id: "coin-pouch",
    productType: "coin_bundle",
    displayName: "Coin Pouch",
    subtitle: "500 Coins",
    description: "A small boost for your journey.",
    artwork: "coin-pouch",
    backgroundTheme: "blue",
    currencyType: "real_money",
    platformProductId: "card_crunch_coin_pack_500",
    localizedRealMoneyPrice: "$0.99",
    coinAmount: 500,
    unlockEntireCollection: false,
    sortOrder: 420,
    tabs: ["coins"],
    enabled: true
  },
  {
    id: "coin-mountain",
    productType: "coin_bundle",
    displayName: "Coin Mountain",
    subtitle: "5,000 Coins",
    description: "The ultimate coin haul.",
    artwork: "coin-mountain",
    backgroundTheme: "teal",
    currencyType: "real_money",
    platformProductId: "card_crunch_coin_pack_5000",
    localizedRealMoneyPrice: "$4.99",
    coinAmount: 5000,
    unlockEntireCollection: false,
    sortOrder: 430,
    tabs: ["coins"],
    enabled: true
  },
  {
    id: "starter-booster",
    productType: "mixed_bundle",
    displayName: "Starter Booster",
    subtitle: "A defined three-part bundle",
    description: "1,200 Coins + 1 Mystery Pack + Pink Arcade Full Deck.",
    artwork: "starter-bundle",
    backgroundTheme: "pink",
    currencyType: "real_money",
    platformProductId: "card_crunch_starter_booster",
    localizedRealMoneyPrice: "$3.99",
    coinAmount: 1200,
    cardsAwarded: 1,
    collectionId: "pink_arcade",
    unlockEntireCollection: true,
    contents: ["1,200 Coins", "1 Mystery Card Pack", "Pink Arcade Full Deck"],
    quantityLimit: 1,
    badge: "STARTER",
    sortOrder: 510,
    tabs: ["coins"],
    enabled: true
  },
  {
    id: "weekend-deal",
    productType: "mixed_bundle",
    displayName: "Weekend Deal",
    subtitle: "800 Coins + 3 Mystery Packs",
    description: "A clearly defined rotating bundle.",
    artwork: "weekend-bundle",
    backgroundTheme: "gold",
    currencyType: "real_money",
    platformProductId: "card_crunch_weekend_deal",
    localizedRealMoneyPrice: "$2.99",
    coinAmount: 800,
    cardsAwarded: 3,
    unlockEntireCollection: false,
    contents: ["800 Coins", "3 Mystery Card Packs"],
    quantityLimit: 1,
    offerDurationMs: 3 * 24 * 60 * 60 * 1000,
    badge: "2D 23H",
    sortOrder: 520,
    tabs: ["coins"],
    enabled: true
  }
];

export const STORE_PRODUCTS = Object.freeze(PRODUCTS.map((product) => Object.freeze({
  cardsAwarded: 0,
  unlockEntireCollection: false,
  enabled: true,
  ...product,
  tabs: Object.freeze([...(product.tabs ?? [])]),
  contents: Object.freeze([...(product.contents ?? [])])
})));

export function getStoreProduct(productId) {
  return STORE_PRODUCTS.find((product) => product.id === productId) ?? null;
}

export function getStoreProductsForTab(tabId) {
  return STORE_PRODUCTS
    .filter((product) => product.enabled && product.tabs.includes(tabId))
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getNextDailyReset(now = Date.now()) {
  const date = new Date(now);
  date.setHours(STORE_CONFIG.dailyResetHour + 24, 0, 0, 0);
  return date.getTime();
}

export function getStoreDayKey(now = Date.now()) {
  const date = new Date(now);
  return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
}
